name: flutter_map_user_location_example
description: Demonstrates how to use the flutter_map_user_location plugin.

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_map_user_location:
    path: ../

flutter:
  uses-material-design: true
